# Generated by Django 5.1.5 on 2025-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_participant_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='event_images/'),
        ),
    ]
